[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]

command = """
mkdir -p envs && \
printf 'FLAVOR="%s"\n' "$FLAVOR" > envs/dart-define.env && \
printf 'LOCKET_API_KEY_IOS="%s"\n' "$LOCKET_API_KEY_IOS" >> envs/dart-define.env && \
printf 'LOCKET_API_KEY_ANDROID="%s"\n' "$LOCKET_API_KEY_ANDROID" >> envs/dart-define.env && \
printf 'LOCKET_API_KEY_WEB="%s"\n' "$LOCKET_API_KEY_WEB" >> envs/dart-define.env && \
printf 'FIREBASE_API_KEY_IOS="%s"\n' "$FIREBASE_API_KEY_IOS" >> envs/dart-define.env && \
printf 'FIREBASE_API_KEY_ANDROID="%s"\n' "$FIREBASE_API_KEY_ANDROID" >> envs/dart-define.env && \
printf 'FIREBASE_API_KEY_WEB="%s"\n' "$FIREBASE_API_KEY_WEB" >> envs/dart-define.env && \
printf 'GOOGLE_SHEET_KEY="%s"\n' "$GOOGLE_SHEET_KEY" >> envs/dart-define.env && \
flutter build web --release --dart-define-from-file envs/dart-define.env
"""
publish = "build/web"
