[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]

command = "flutter build web --release --dart-define-from-file envs/dev.env"
publish = "build/web"
