// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:do_ai/constant/env.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final web = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.web,
    appId: '1:700367463733:web:83883df4fe42c446dc987c',
    messagingSenderId: '700367463733',
    projectId: 'doainext',
    authDomain: 'doainext.firebaseapp.com',
    storageBucket: 'doainext.firebasestorage.app',
    measurementId: 'G-RXXDCKBXVL',
  );

  static final android = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.android,
    appId: '1:700367463733:android:18fb1403a4a6be71dc987c',
    messagingSenderId: '700367463733',
    projectId: 'doainext',
    storageBucket: 'doainext.firebasestorage.app',
  );

  static final ios = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.iOS,
    appId: '1:700367463733:ios:a4dab95551341464dc987c',
    messagingSenderId: '700367463733',
    projectId: 'doainext',
    storageBucket: 'doainext.firebasestorage.app',
    iosBundleId: 'letrungdo.doAI',
  );

  static final macos = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.iOS,
    appId: '1:700367463733:ios:a4dab95551341464dc987c',
    messagingSenderId: '700367463733',
    projectId: 'doainext',
    storageBucket: 'doainext.firebasestorage.app',
    iosBundleId: 'letrungdo.doAI',
  );

  static final windows = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.web,
    appId: '1:700367463733:web:a43cce6dbe627a9adc987c',
    messagingSenderId: '700367463733',
    projectId: 'doainext',
    authDomain: 'doainext.firebaseapp.com',
    storageBucket: 'doainext.firebasestorage.app',
    measurementId: 'G-HK23TT9QFN',
  );
}
