// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:do_x/constants/env.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static final web = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.web,
    appId: '1:66571675093:web:17b59d0335bbfca2da495c',
    messagingSenderId: '66571675093',
    projectId: 'do-appx',
    authDomain: 'do-appx.firebaseapp.com',
    storageBucket: 'do-appx.firebasestorage.app',
    measurementId: 'G-0CPJ0B5YLC',
  );

  static final android = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.android,
    appId: '1:66571675093:android:4ba80d0aec0d028fda495c',
    messagingSenderId: '66571675093',
    projectId: 'do-appx',
    storageBucket: 'do-appx.firebasestorage.app',
  );

  static final ios = FirebaseOptions(
    apiKey: Envs.firebaseApiKey.iOS,
    appId: '1:66571675093:ios:de9146784dbf9abeda495c',
    messagingSenderId: '66571675093',
    projectId: 'do-appx',
    storageBucket: 'do-appx.firebasestorage.app',
    iosBundleId: 'inc.do.x',
  );
}
